### ISSUE TITLE
this page is trying to load scripts from unauthenticated sources

### ISSUE THREAD

**Issue by mrzeeshanplus** [felladrin/online-visitors-counter#2]
I am not able to use this on https

**Comment by felladrin** [comment]
Hi there, thanks for reporting.

Just to check, are you loading the script like this?
```
<script src='http://example.com/ovc/counter.js'></script>
```

If so, try removing the `http:`:
```
<script src='//example.com/ovc/counter.js'></script>
```

**Comment by mrzeeshanplus** [comment]
<script src='//example.com/ovc/counter.js'></script>
I have tried this too
any other solution?
or just tell me how can make it to just show the online users number ..because when i am clicking on the button i am getting "this page is trying to load scripts from unauthenticated sources" ?
its fine if it will not show where the users are.
can you tell how to do?
i am not a programmer 

you can check here https://electronics2electrical.com/ 
<script src='//electronics2electrical.com/ovc/counter.js'></script>
I have tried this too
<script src='https://electronics2electrical.com/ovc/counter.js'></script>

**Comment by felladrin** [comment]
That's strange that the error only occurs when trying to open the 'where are the visitors' div.
Well, you can disable the 'click' function from the counter by removing the code:
```
button.onclick = function ()
{
        createOnlineVisitorsIframe();
        return false;
};
```
From the file [ovc/counter.js](https://github.com/felladrin/online-visitors-counter/blob/master/).

Note you'd need to remove it from the two blocks (starting at line 79 and 91):

![image](https://user-images.githubusercontent.com/418083/31262434-4a6d826a-aa31-11e7-961c-eea023836629.png)

**Comment by mrzeeshanplus** [comment]
thanks alot finally it works. nice

**Comment by felladrin** [comment]
Sure, you're welcome. If you have anymore questions, feel free to open new issues.
