### ISSUE TITLE
how can i set a position on a page ?

### ISSUE THREAD

**Issue by mrzeeshanplus** [felladrin/online-visitors-counter#3]
like i want to fixed a position at sidebar .. i do not want to show it whole website ..how can i do that?
thanks in advanced .

**Comment by felladrin** [comment]
You can manually place this code anywhere on your template:
`<a id="online-visitors-counter"></a>`
And it will be used as the counter.
No other element will be created.

Reference: https://github.com/felladrin/online-visitors-counter/blob/master/ovc/counter.js#L87

**Comment by mrzeeshanplus** [comment]
thanks alot again

**Comment by felladrin** [comment]
You're welcome!
