### ISSUE TITLE
sometime last_activity and id are NULL

### ISSUE THREAD

**Issue by alecos71** [felladrin/online-visitors-counter#7]
I did see that sometime last_activity and id are NULL 

my patch at this moment is below:

`$count = $db->query('SELECT COUNT() AS visitors, COUNT(DISTINCT page_url) AS pages FROM online WHERE last_activity IS NOT NULL AND id IS NOT NULL')->fetch(PDO::FETCH_ASSOC);`

I solved in this manner, maybe the best way is perform on delete...

Let's me know something asap.

Thank you!

**Comment by felladrin** [comment]
Fixed in #8.

**Comment by alecos71** [comment]
Would be better perform a delete query on NULL values of last_activity and id?

The query select is only a simple patch e doesn't provide a true solution...

What do you think about?

[online.zip](https://github.com/felladrin/online-visitors-counter/files/7907926/online.zip)

I attach here a sqlite db which is affected by this bug... and add 2 screenshot showing the issue...

![Online 01](https://user-images.githubusercontent.com/9997666/150408378-23823056-135d-4507-b2d0-e4cace785221.png)

![Online 02](https://user-images.githubusercontent.com/9997666/150408410-1ffea19f-e3c9-483c-af98-7d9b757dca73.png)
.
